export type Service = { slug:string; title:string; category:string; description:string; icon:string; priceType:'fixed'|'request'; details:string[] };
export const services:Service[] = [
 {slug:'post-utme-screening',title:'Post-UTME & Online Screening',category:'Admissions',description:'Assistance with Post-UTME applications, online screening and related admission processes.',icon:'🎓',priceType:'request',details:['Application guidance','Online screening assistance','Document and information checks']},
 {slug:'school-fees-acceptance-gst-ent',title:'School Fees, Acceptance Fees & GST/ENT',category:'School Services',description:'Get assistance with school payments and related online academic transactions.',icon:'💳',priceType:'request',details:['School fee payments','Acceptance fee processing','GST/ENT payments']},
 {slug:'course-registration-clearance',title:'Course Registration & Online Clearance',category:'School Services',description:'Support for course registration, online clearance and related student portals.',icon:'📝',priceType:'request',details:['Course registration support','Online clearance','Portal assistance']},
 {slug:'jamb-services',title:'JAMB Services',category:'JAMB',description:'Support for Original Result, Admission Letter, CAPS, Reprinting and other JAMB services.',icon:'📘',priceType:'request',details:['Original Result','Admission Letter','CAPS assistance','Reprinting and related services']},
 {slug:'waec-neco-nabteb-cards',title:'WAEC/NECO/NABTEB Scratch Cards',category:'Examinations',description:'Access examination result-checking cards and related assistance.',icon:'🎫',priceType:'request',details:['WAEC cards','NECO cards','NABTEB cards']},
 {slug:'transcript-original-result',title:'Transcript & Original Result Processing',category:'Documents',description:'Professional assistance with transcript and original-result processing requests.',icon:'📄',priceType:'request',details:['Transcript requests','Original result processing','Application support']},
 {slug:'assignments-projects-siwes',title:'Assignments, Final Year Projects & SIWES/IT Reports',category:'Academic Support',description:'Academic support services for assignments, projects and SIWES/IT documentation.',icon:'💻',priceType:'request',details:['Assignments','Final year projects','SIWES/IT reports']},
 {slug:'state-of-origin-birth-certificate',title:'State of Origin & Birth Certificate Processing',category:'Documentation',description:'Assistance with documentation-related processing requests.',icon:'🪪',priceType:'request',details:['State of origin processing','Birth certificate processing','Application guidance']},
 {slug:'property-services',title:'Property Buying & Selling Services',category:'Property',description:'Support for property buying and selling enquiries in and around Ekpoma and beyond.',icon:'🏠',priceType:'request',details:['Property enquiries','Buying support','Selling support']}
];
