'use client';
import {useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
import {services} from '@/lib/services';

export default function RequestService(){
 const params=useParams<{slug:string}>(); const router=useRouter(); const service=services.find(s=>s.slug===params.slug);
 const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [details,setDetails]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace(`/login?next=/services/${params.slug}/request`);return;}setEmail(user.email||'');const {data}=await supabase.from('profiles').select('full_name,phone').eq('id',user.id).maybeSingle();setName(data?.full_name||'');setPhone(data?.phone||'');})();},[params.slug,router]);
 if(!service)return <main className="section"><div className="container"><h1 className="text-2xl font-black">Service not found</h1></div></main>;
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return;}const {data:dbService}=await supabase.from('services').select('id,price').eq('slug',service.slug).maybeSingle();if(!dbService){setError('This service has not been configured in the database yet. Run the Build 2 SQL setup first.');setLoading(false);return;}const reference=`PCR-${Date.now().toString().slice(-10)}`;const {error}=await supabase.from('orders').insert({reference,customer_id:user.id,service_id:dbService.id,status:'pending',payment_status:'unpaid',amount:dbService.price||0,form_data:{full_name:name,phone,email,request_details:details}});if(error)setError(error.message);else router.push('/dashboard/orders');setLoading(false);}
 return <main className="section bg-slate-50"><div className="container"><div className="mx-auto max-w-2xl rounded-3xl bg-white p-6 shadow-soft sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0757d5]">Service request</p><h1 className="mt-2 text-3xl font-black">{service.title}</h1><p className="mt-2 text-sm text-slate-500">Submit your details now. Payment will be connected in Build 3.</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-bold">Full name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="block text-sm font-bold">Phone number<input required value={phone} onChange={e=>setPhone(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="block text-sm font-bold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="block text-sm font-bold">Request details<textarea required value={details} onChange={e=>setDetails(e.target.value)} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" placeholder="Tell us what you need and include any relevant information."/></label><button disabled={loading} className="w-full rounded-xl bg-[#0757d5] px-5 py-3.5 font-bold text-white disabled:opacity-60">{loading?'Submitting…':'Submit service request'}</button></form></div></div></main>
}
