import {redirect} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import RequeryPaymentButton from "@/components/payments/RequeryPaymentButton";

export default async function AdminPayments({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login?next=/admin/payments");
 const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle(); if(profile?.role!=="admin")redirect("/dashboard");
 const admin=createAdminClient(); const params=await searchParams; const q=String(params.q||"").trim(); const status=String(params.status||"").trim();
 let query=admin.from("payments").select("id,order_id,reference,provider,amount,currency,status,gateway_response,paid_at,created_at,orders(reference,customer_id,profiles(full_name,phone),services(title))").order("created_at",{ascending:false}).limit(200);
 if(status)query=query.eq("status",status as any);
 if(q)query=query.ilike("reference","%"+q+"%");
 const {data:payments}=await query;
 const all=payments||[]; const paid=all.filter(p=>p.status==="paid"); const pending=all.filter(p=>p.status==="pending");
 const paidValue=paid.reduce((n,p)=>n+Number(p.amount||0),0);
 return <div>
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#0757d5]">PAYMENT MANAGEMENT</p><h1 className="mt-1 text-2xl font-black">Payments</h1><p className="mt-1 text-sm text-slate-500">Monitor Paystack transactions linked to customer orders.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-white px-4 py-3 shadow-sm"><p className="text-xs text-slate-400">Shown</p><p className="font-black">{all.length}</p></div><div className="rounded-xl bg-white px-4 py-3 shadow-sm"><p className="text-xs text-slate-400">Paid</p><p className="font-black">{paid.length}</p></div><div className="rounded-xl bg-white px-4 py-3 shadow-sm"><p className="text-xs text-slate-400">Pending</p><p className="font-black">{pending.length}</p></div><div className="rounded-xl bg-white px-4 py-3 shadow-sm"><p className="text-xs text-slate-400">Paid value</p><p className="font-black">₦{paidValue.toLocaleString()}</p></div></div></div>
  <form className="mt-5 flex flex-wrap gap-2"><input name="q" defaultValue={q} placeholder="Search payment reference…" className="min-w-[220px] flex-1 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"/><select name="status" defaultValue={status} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="">All statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select><button className="rounded-xl bg-[#0757d5] px-5 py-3 text-sm font-bold text-white">Filter</button>{(q||status)&&<Link href="/admin/payments" className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold">Clear</Link>}</form>
  <section className="mt-5 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-4">Payment</th><th className="p-4">Customer</th><th className="p-4">Order</th><th className="p-4">Amount</th><th className="p-4">Status</th><th className="p-4">Date</th><th className="p-4">Action</th></tr></thead><tbody>{all.map((p:any)=>{const order=p.orders; const profile=order?.profiles; const service=order?.services; return <tr key={p.id} className="border-b last:border-0"><td className="p-4"><p className="font-black">{p.reference}</p><p className="text-xs text-slate-400">{p.provider}</p>{p.gateway_response&&p.status!=="paid"&&<p className="mt-1 max-w-xs text-xs text-red-600">{p.gateway_response}</p>}</td><td className="p-4"><p className="font-bold">{profile?.full_name||"Unknown"}</p><p className="text-xs text-slate-400">{profile?.phone||"No phone"}</p></td><td className="p-4"><Link href={"/admin/orders/"+p.order_id} className="font-bold text-[#0757d5] hover:underline">{order?.reference||"Order"}</Link><p className="text-xs text-slate-400">{service?.title||"Service"}</p></td><td className="p-4 font-black">{p.currency} {Number(p.amount||0).toLocaleString()}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize">{String(p.status).replace("_"," ")}</span></td><td className="p-4 text-slate-500">{new Date(p.created_at).toLocaleString()}</td><td className="p-4">{p.status!=="paid"&&<RequeryPaymentButton orderId={p.order_id}/>}<Link href={"/admin/orders/"+p.order_id} className="mt-2 inline-block text-xs font-bold text-[#0757d5]">View order</Link></td></tr>})}</tbody></table></div>{!all.length&&<p className="p-10 text-center text-sm text-slate-500">No payments found.</p>}</section>
  </div>;
}
